// src/shared/constants/errorCodes.js
const ERROR_CODES = {
    // Authentication
    AUTH_TOKEN_MISSING: 'AUTH_001',
    AUTH_TOKEN_INVALID: 'AUTH_002',
    AUTH_TOKEN_EXPIRED: 'AUTH_003',
    AUTH_INVALID_CREDENTIALS: 'AUTH_004',
    AUTH_USER_NOT_FOUND: 'AUTH_005',

    // Authorization
    AUTHZ_INSUFFICIENT_PERMISSIONS: 'AUTHZ_001',
    AUTHZ_ROLE_REQUIRED: 'AUTHZ_002',

    // Validation
    VALIDATION_REQUIRED_FIELD: 'VAL_001',
    VALIDATION_INVALID_FORMAT: 'VAL_002',
    VALIDATION_OUT_OF_RANGE: 'VAL_003',

    // Business Logic
    BIZ_USER_ALREADY_EXISTS: 'BIZ_001',
    BIZ_INSUFFICIENT_FUNDS: 'BIZ_002',
    BIZ_MARKET_CLOSED: 'BIZ_003',
    BIZ_ORDER_LIMIT_EXCEEDED: 'BIZ_004',
    BIZ_INVALID_OPERATION: 'BIZ_005',

    // Technical
    TECH_DATABASE_ERROR: 'TECH_001',
    TECH_EXTERNAL_SERVICE_ERROR: 'TECH_002',
    TECH_TIMEOUT: 'TECH_003',

    // Rate Limiting
    RATE_LIMIT_EXCEEDED: 'RATE_001'
};

module.exports = ERROR_CODES;